version: '3.9'

services:
  my-c-dev-02-ubuntu:
    build: 
      context: ./build
      args:
        - __WORKSPACE_FOLDER=${WORKSPACE_FOLDER}
    volumes:
      - ../../:/${WORKSPACE_FOLDER}/
      - /var/run/docker.sock:/var/run/docker.sock
    command: [ sleep, infinity ]
